M1618578639232109156 = 868
FOzLLQxkZcQRKLMjZqHHuLILPvsPhiUkegPaUMBmFRGyeaqdMZZZVAbADXQFBDPunsLmZHWpyZRymkF154 = "qGFMniKkajtWWTmiyaubpnAQBnjnEnPUMYwUPPNIqJDDoioInVlAHOeDJMOaapUBGyGjVcsmjgpWmzd"
AaaaAaAaAaAaAAAAaaAaAAaAAAAAaAaaaaaaaAaAAAaAAAaAAaaAaaAaaaaAAaAAaAAaAaaAaaAAAAaaAaaaAaAaaaaAaaAAaaAaAAaAaAaaAaAaAaaAAaAaaAaaaaaAaaaAaaaAAaaAAAAAAaaAAAAa = "IjAXqOsNXqwXmSExslIWEYucoZVojNbOlMUdoWXORjbWOkYtHFtOftFOgrEzIqaDTbzWcAnaJhkRnYk"
W150 = "kUGtbVsAUQlAkzxGTnLwThqWuUAYYKYZRuHrHewCGjKfogMUEfiMrEaTeTqzTzLfvJjHGfeTCGJCpvC"
B16185786392319252148 = "QzOoAqsuRqCNmdFsoUVzOZiTbjPpFxsrgFlepdRQPEbIOIKOPMNyxHXLyzIfobCHjCluIullQejexFP"
aaaAAaaAAAAAAAaAAAaaaAAAAaaAAaAAAAAAAaAaAaAAAAaaAAaAAaAAaaAaaAaAAaAAAaAaAAaAAAAAAAAaAAaAaAaaaAAaaAaAAAaaAAaaAaAAAAaAaaAaaAAaaaAaAAaaaAAaAaAaAAaAaa = "okBOMClZFGzhkzFZszGSfgovcQApjMoCSLeysOBRPdTcvjOrOjjMkgqnAeHirZaQJmorLURGzfOkgpM"
RKzEGXFiIlcQkfWVxcFUeprkHhSyNCLccOaNXyiXZsxUWSWAxQqRzvULZOzIDPDzDMzPGTLZKErnVHf144 = "qKtBdCudQsPieXRYIEpibdOYAqMJjfLnNOpuCnXjeLmBuuEsAAGAqjWdoCsJYhieqZMMsWBXxnPEfDd"
d16185786392317677142 = 207
q140 = "EwDufQAMNpzhQpNPNixKzRmErWLuJnMorlqSblacLwldGFVsjQrydurRvwTltlfZAzNvVpCEtCsbrtu"
AAaAAAAaAaaAAAAaAaaAaAaAaAAAaaaAAAaAAaaaaaAAAAAAAAAAAaaAaaAaAaaAAAAAAAaAaAAaAaaaAaAAAAAaAAAaAaaaaAaaaAaAaaAAaaAaAaAAaAAaAAAAAAAAaAAaAaAAAa = 57
AAAaAaaaaaaaAaAaaaAaaAaAaaAaAaaaaAAaAAaAAAaaAAaaAaaAAaaaAAAaaAaAaAAaaAaaaaAAAaaaAaAAaaaAAAAaAaAAAAaaaAAAAAaaAAAAAAaAAaAAaaaaaAaaAAAAaAaA = "NyAFCEovkoFjNGZopUbnFdBUNnTyNRCLuTGbqNiddIuHtlhbUvwmNuVVEwHSskHviZwPTQUTYOnuvax"
aAaaAaaaaAAaAaAAAAAAAAaAaaAaaaAAaaaaAAaAaAaAAAAaAAaaAAAAAAaaAAAAAaAAaaaAaaaaAaAaaaaAaAAaAAaaaaaAAAaAaaaAAaAAaaAAAaAaAAAAAaaaaAaAaAaAaA = "kmusiaHwHKVfonFJOdRtVHlpvSMlAtHdXflaZhowZGrDoTkkfJobngLtbypYZheMSNwUjgBFMtsFnCH"
aAAAaaAaaAaaAaAAAAAAAAaAAaAAAAAAAaaaAAAAAAaAaaaAaaAAaaAAAaaAAAAaAaaaAAAaAaAAAaaaAaaaAaaaAAaAaaAAAaaaAAaAAAaAAaaaaAaAaAaAaaAaAaAaaAAa = "ntUwlhgaNztXXQyCRIsWdNRlknWPUVVVqOnxrosCnBxXymDhBgLENkBpAXnyzjVrjqOpnAeLCzOvWZw"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO = 309
a128 = "NIGGXflFNbchdVWLHCLAdzREZtnPtRLiSuXcdoBTTBKNOsPAmXyJoedcKAmeAaMSAjpXWpEfBnJoXLS"
b126 = "SnOHcjTuCpKstDsiJrcLyqQlrxoquoGbhPntNfXXpEZFWXmXARZghpdDldMEgqSsSwkLukfTgObpMXF"
z124 = 686
AaAaaAAaAAAaAaAaAaAaAAAaaaAAAaAaAaAaaAaAAaAAaAaaAaaAaAaAaaAaAAAaaaaaaaAAAAAaAAaaaaAAAaAAAAaAaAAaAAAaaAaAAAAaaaaaaAAaaaaAAa = "dpsIeTMjtGSaCrgdmCIcbhcxIjeIiDTbHeBMFRZWVvAscDWZjXsstfbTSzhLqIdhvziRlOyCBeiTkvE"
qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq = 474
D118 = 435
a116 = "cAqVsnagmYSyoGPUWDyvLhehENnCtMIHRbtxlhBVYRAdADnPLHGRLbzdhDchSJOYOLpGKCTfebEGkgn"
AAAAaaAAAaAaAAaAaAaAAAAAAAAaAAaaAAAAAaaAAaAaAaaAAaAAaaaAAaAaaaaaAAAaaaaaaaAAAaaaaaaaaaAaaaaAaaAAAaAAaaaAaAAaAaAaaa = 243
lllIIlIlIIlIlllIllIIIllIIIIIllllllllllllIllIIlIIIIIIlIlllIlIIIlllIIIIllIIIlIIlIIIlIllIIIIIllIIIIlllIlIlIlIllllII = 417
UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU = 743
ouhUztpILgEYjWcRArbRzMzqyJtiwtwylTYmszQiIGvpmyUbPWdqtPPkGukPkYjFiJJqXEotowsoHjw108 = 500
VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV = 243
IIIlllIIllIIIlllIIIIlIllllllllIlllIIIIllIIlllIIllIIlIIlIllllIlllIllIlIlIIlIIIllIIIlIIIlIlIllIllIlIlIlIIl = 162
U16185786392308218102 = 340
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm = 692
nyzMzqDzwfSrGADAgttCOBGeQeDJYQofmDMBxUQxzAmsqzBFDvWPoKiDnpLfZdGOkaDhJkYTUuyeSXI98 = 405
ozkPVubdfSjySvUmMSJLqcOCYyaFWqZQfcYUfdyKVAQUhxJzyhcshUqBavUtSUFqZMRuNKqOYzuzDax96 = "uUMvdeXyhkqqpOcMAzHKBypjbjVNAuZoXEsLzfFTqlquHPyhAZuUJcifySIuOetfhNaenjLokpBQYAQ"
YlTeaBjXfFaibHaZZARoqbzrcyGHPqaUJRSRYyMEuKDbECEFoCEGqXfRZDhseDwdSLsllyKvTCkdGci94 = "EErETNaVmmXhkkZiHTSndGQGVBJswxiCVYjXTQbBtpdmvcCZfzDaxUeKTvHaNhwyhRPrmdCZbZhXXEV"
P1618578639230600492 = "xxDtDLDAHdvJdtxSZDrWcfjgTfEfFjcXiGAMhvFPeQIsvwBBpHCGCipIJYGsQNGcZwqVWDTpBYzVKzl"
lIlllIlIIllIlIlllIIlIIlIIIIlllIlllIIIlIIlIIllIlllIlIlIlIIIllIIlIIlIIIIIIlIllllllllIIlllIIl = "oMXBUjKKeYefvcQvWFUjaBHbuxMvBsJFRfpwjmIKIcgpaBVwsuqNYMhLSrEtFmGhkWFdvkagEMAIwbE"
diqyhDxWYcjlfMPoZttBSkUZXolpiJRCWRzbctZVMnRjRRNOWRhXEHXMqvRjqgjkbjWCpbYwkoDraEF88 = "vKoHJSkABXahOkiOWaYVdZuQOmlGCRvjCWYOcoBADqUtbZeanokDCZfRqMAYwnKJnmKFRFCkDGqruuo"
aAAAAAaaAAaAaaaaAaAAAaaAAAaAAaaAaAaAaAaAaaaAaAaAAAAaaAaaAaaAAaAAaAAaAAaAAaaAaAAaAAaAaa = 494
AaaaAaaAaAAAAaaaaaAAaaAAaaAAAAAaaaaaAaaaaAaAAAaaAaAAaAAaAaaAaAAaAAaaAaAaAAAaaAAAAAAa = 348
AAAaaAaaAAaAaaAAaaAaAAAAAAAaaAAAaaaAAaAaaAAaAAAaAAAAAAaAaAaAaaaAaaaaaAAaaAaAAaAaaA = 379
aAAaaAAaAAAaaAaaAAaaAAaaAaAaAAAAAaAaAaAAAaaAAaaaAAAaAAaaAAaaAAaaAAaAAaAAAaAaaAAA = 423
IllIIIllIllIIIIlIlIlllIlIlIllIllllIllIlllIllllIlIIlllllIlIIIlIlIlllIlIllIlIIII = "lKkKfiHqiSKyuEjoSyuplFtnyocoyqVktGUwALwrghbCbByLNcYPECrtWueqDLCJeZbirnBkoLkJJhz"
Q76 = "JSayRvXeMJXyTygWEcIsalHxQjYnwveHzfFUuwLwoDSOaTzOpZdUTxTLdBdObkPhQsNuiULakYLlwDB"
AaAAaAaaaAaaaaAaAaaaaAAaaaAaAaAaAaaaaaaAAAAaAAaAAaAAaAAAAAaaAAaAaaaAAAAAaa = "qaEpOLhGXijxLiEnHAXEdpkugzxdzadrNQcLvflbOyuJwYQCCxsITXwbFqoTHHMRWURsGNzAHxMgDZv"
w161857863923011172 = "zJYGrolKoijQRVbWrnnOAUxsDwBTlZSzuuLBNebJZLbWCnhlsLuzeLuEtPCarJsjXcjIppcOInXDXiB"
AaaAaaaaaaaaaaaAAAaaaAaaaAaaAAaAAaAAaAaAaAAAAAaAaAAAAaaaaaAAAAAAAAaaAA = 970
pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp = "MQEcdCPtkTOKcWQGmJDhhvGsMXkhKOpGRwqfQKSsRJwluXZmpyJFrzZyceQFLcORRLBMlOGhltAKAtZ"
aaAaAaAaAaAaaAaAAaaAaaAAaaAAaaAAAAAaAaaAaAAAaaaAAAAAaAAaAAaaaaaAaa = "tbOZUudXiAUextxcUWohdFYYGkYYZXmTBnIkoKtGwJExDWFEwKEqqSQccXyaGjvLAEZCdXtqyWXmRTE"
aAaaAAaaAAAaAAaAAaAaAaAaAAAAaAAaAAaAaAaAaaaAAAaaAAaaAAaAAAaaaaAa = "LKQfNKTkBkXkFWrUYVIhRSEFsmotLMKiulPLqmMyDxUtGbZdQQmspdOnJnNnwDhGDBiFMpGOLQaikPE"
IlllIlIIIlIIIlIIIllllIIIlllIIllIlIlIllllllIIlllIllllIlllIIlIlI = 182
AnfmokbraUiYtygTEqBEIyYeueOyztGoclCvmUAtzVPfaCMDkJdvCtLWTnvwMQVNNeRlGOqxAiqptVp60 = "gzcwTlODiVfZdZGcmBnqquADFrajaLdXsLWtJLjmDnQpAYgRGXIXemniOJjPkkiONWMLWllCspSfodf"
aaAaaAaaAAAaaAaAaAAaAaaAaaaAAaaAAaaaaaaaAaaAaaaAaAaaaAAaAA = "UDaGaauWxupWEUZzsQqMIiHprUVgpWBdqrbeeBXxRQnUWrRHbIbeLwEwANZNuBgyHYDlfduDBNoqBct"
L56 = "pQZTNJhmiSpmarPBzmrEcIIVbkOaAyaLXYqpODUSUCOaqWnmbDrwLWWOcBZgQFXNxhKgyvdPfrbkAjC"
jEGSkDaCynjNikyjNsdnLvxGnzdqoWNygfYpYAEoApOWCjfRnFqDEEyWwwUqrwdOVvvZxzNOWeQRsaZ54 = 305
AaAAAAAaaAaaAAAaAAAaAaAaaAaAaaAAAaaaAaaaaAaAAaAaAaaa = "siEfZoztnwplnAzwQZeljbrBNoxWUtGrWHMCiaHfDJsHcXvChglFqYQxiwqdjrdQsfelImKBJuHjvyJ"
T50 = "KLSJljTHuGIrSLgIzvLxmuZonBEGagNmSiBUJJonqhhsHtiGgHdbczdmofgTRisEESofReXyLZIsBIX"
IllIIIlIIlIIIllIlIIIlIllIIIIIIlIIIIllllllllIlIlI = 151
lIIIIlIIIIIIllIlIllIIIlIIllIlIIIIIlIlIIllIIlll = 208
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww = 441
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa = "YRehwWOVdWAACWXLBEMylPKDwIdGExXBHBcJfXKDYebbJtJiNyoRGGsIBVfUvSNEPgdTENAaDSGzaay"
Y1618578639229331540 = "kTxSBOxhsMPJAmNPSygxBJIIUBHUlyuQsrXlpPncpfSeXWHPKGPxLlGEcWZOzQsLIVLcwXQkSVVVfdV"
D38 = 341
K36 = "CHLCcmIuTHXMLNMjhAnBlkbmhUUoJKSfjzeISUGqWRLRcxlnNFsuaQZVsWPXvjPSIFnhOglMymGgWVW"
W1618578639229249234 = "vBcjlQOXUqSaxlXMKdLaNZPOsouwFNaBpMvDJHUdoUqcqUrOMAMbCKcZEJicKxFPRlLVzIRZBpTBAXP"
aaaAAAAAaAaAaAAaAaaaaAaaAaAAaAAA = "OmlunNiEjdUILAMNGBAofCFENBYKPXyZZUTMEotnjyBrsAHxOItSQUCRFzxLZOpMtHBMxUZGCHtCZRh"
eeeeeeeeeeeeeeeeeeeeeeeeeeeeee = "JhgdncwDKEydjWdhRqyhMVwdccoorlIWbVEfuETVjwjfXdeYUQeRfSRcwafgboFKrOaeTuizoQMZEXi"
u28 = 357
W1618578639229081926 = "cPxLtagCrxFNzmKywMUJuYAMYKQguHmkgKAkTnZcduencAwkRVxuLrSUIgihrmibXZJEmsIXdYxyKIb"
jjjjjjjjjjjjjjjjjjjjjjjj = 215
IIlIIIlIIIlIllIlIIlIll = 678
IlIllIlllllllIlllIII = "alvHMydUFfEGFfzadiKmqznOAgxNZsKngXKgngaYZqvHpVrVxHdVeCTnrsFoYkTfNvzbjoCjtEMCPvS"
FFFFFFFFFFFFFFFFFF = 219
yahqcYsCYZDfXuyVoJWEkvgPIkzqKnTNoBCZvsFsTcVIzGDnHdWKCEsjOgPegAITIzDameflilkOxZh16 = "QkkihByVIJBQcaQDnaEpDVYCsZVtanxoosGYdLsAXnpDjcvwwUuLZXOGggCeNdOKSXtMFzhxDcnQPXH"
MMuUTnwVfhqOGaoTYNGKcLllWtEnturzRmaAzStMFPNKFoallPNisfrPtoqRygeALmodbbgmEesLnba14 = 379
y1618578639228852512 = "YVRofYkhPorewNcAhUZwqQWZNtpIXtPyFkVnNZVqoFHQiwuBdEEPDkdxDrkQnXpqzXYfhBuYUfcHAAF"
aaaAAaaaaA = "obxuVgOvgTozAvMpLJwQxWGwZdCssMdqoxCgifyAoZGUmKBXUwqnYtqYWdAuCMBNeoJnZtEuZRndoab"
ZZZZZZZZ = "HTkdyyjlfYvFCeCuBuXItXPHgWiOyCByRszhnwFJSziyRNIwoJdSMzLwEqZKNdbNZpiiSNxFpXhtAnD"
L6 = 388
ttpWRAhYOcZWVOibsNeHoFQlwsfiSKyugfEeezLByGLPenvyUtibOvNQGBHlnwkwOYyGIVKyDBOKooY4 = "hWtnxXCVKBnKxyVXCtHWcPGmUFQIkcaBSkdenzBGfIyhOrjjsawOladQSqrksTZrKqOjNfZaQvCVFWk"
u2 = 61

import sys
import time

l = .05
qHYgMhzFrQZdAuWDGCzFtkvGKPqEMoELooTsAvpwypSVTJsijyEBYsiSmNkzLOjRSPHQhmtrDYUXORT2 = .25

def dPrint(string, seconds, wait):
    for character in string:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(seconds)
    time.sleep(wait)

def greetUser():
	dPrint("Hello, Hack MoVal participant. ", l, qHYgMhzFrQZdAuWDGCzFtkvGKPqEMoELooTsAvpwypSVTJsijyEBYsiSmNkzLOjRSPHQhmtrDYUXORT2)
	dPrint("This challenge requires you to de-code some encrypted text. ", l, qHYgMhzFrQZdAuWDGCzFtkvGKPqEMoELooTsAvpwypSVTJsijyEBYsiSmNkzLOjRSPHQhmtrDYUXORT2)
	dPrint("The more text you can de-code, the more points you obtain. ", l, qHYgMhzFrQZdAuWDGCzFtkvGKPqEMoELooTsAvpwypSVTJsijyEBYsiSmNkzLOjRSPHQhmtrDYUXORT2)
	dPrint("Good luck!\n\n", l, qHYgMhzFrQZdAuWDGCzFtkvGKPqEMoELooTsAvpwypSVTJsijyEBYsiSmNkzLOjRSPHQhmtrDYUXORT2)

def questionOne():
	T3 = ''
	dPrint("Decrypt the following message:\tQnuux Fxaum", l, qHYgMhzFrQZdAuWDGCzFtkvGKPqEMoELooTsAvpwypSVTJsijyEBYsiSmNkzLOjRSPHQhmtrDYUXORT2)
	while(T3.lower() != 'Hello World'.lower()):
		dPrint("\nEnter your response:", l, qHYgMhzFrQZdAuWDGCzFtkvGKPqEMoELooTsAvpwypSVTJsijyEBYsiSmNkzLOjRSPHQhmtrDYUXORT2)
		T3 = input("\t")
		if(T3.lower() != 'Hello World'.lower()):
			dPrint("\nSorry, try again.", l, qHYgMhzFrQZdAuWDGCzFtkvGKPqEMoELooTsAvpwypSVTJsijyEBYsiSmNkzLOjRSPHQhmtrDYUXORT2)
		else:
			dPrint("Congrats! Give the following code to the facilitator:", l, qHYgMhzFrQZdAuWDGCzFtkvGKPqEMoELooTsAvpwypSVTJsijyEBYsiSmNkzLOjRSPHQhmtrDYUXORT2)
			dPrint("\tJulius Caesar Cipher\n\n", l, qHYgMhzFrQZdAuWDGCzFtkvGKPqEMoELooTsAvpwypSVTJsijyEBYsiSmNkzLOjRSPHQhmtrDYUXORT2)
			True

def questionTwo():
	T3 = ''
	dPrint("Decrypt the following message:\tAlfa Lima Papa Hotel Alfa Bravo Echo Tango", l, qHYgMhzFrQZdAuWDGCzFtkvGKPqEMoELooTsAvpwypSVTJsijyEBYsiSmNkzLOjRSPHQhmtrDYUXORT2)
	while(T3.lower() != 'Alphabet'.lower()):
		dPrint("\nEnter your response:", l, qHYgMhzFrQZdAuWDGCzFtkvGKPqEMoELooTsAvpwypSVTJsijyEBYsiSmNkzLOjRSPHQhmtrDYUXORT2)
		T3 = input("\t")
		if(T3.lower() != 'Alphabet'.lower()):
			dPrint("\nSorry, try again.", l, qHYgMhzFrQZdAuWDGCzFtkvGKPqEMoELooTsAvpwypSVTJsijyEBYsiSmNkzLOjRSPHQhmtrDYUXORT2)
		else:
			dPrint("Congrats! Give the following code to the facilitator:", l, qHYgMhzFrQZdAuWDGCzFtkvGKPqEMoELooTsAvpwypSVTJsijyEBYsiSmNkzLOjRSPHQhmtrDYUXORT2)
			dPrint("\tNATO Alphabet\n\n", l, qHYgMhzFrQZdAuWDGCzFtkvGKPqEMoELooTsAvpwypSVTJsijyEBYsiSmNkzLOjRSPHQhmtrDYUXORT2)
			True

def questionThree():
	T3 = ''
	dPrint("Decrypt the following message:\x16185786392284158=", l, qHYgMhzFrQZdAuWDGCzFtkvGKPqEMoELooTsAvpwypSVTJsijyEBYsiSmNkzLOjRSPHQhmtrDYUXORT2)
	while(T3.lower() != 'Base32'.lower()):
		dPrint("\nEnter your response:", l, qHYgMhzFrQZdAuWDGCzFtkvGKPqEMoELooTsAvpwypSVTJsijyEBYsiSmNkzLOjRSPHQhmtrDYUXORT2)
		T3 = input("\t")
		if(T3.lower() != 'Base32'.lower()):
			dPrint("\nSorry, try again.", l, qHYgMhzFrQZdAuWDGCzFtkvGKPqEMoELooTsAvpwypSVTJsijyEBYsiSmNkzLOjRSPHQhmtrDYUXORT2)
		else:
			dPrint("Congrats! Give the following code to the facilitator:", l, qHYgMhzFrQZdAuWDGCzFtkvGKPqEMoELooTsAvpwypSVTJsijyEBYsiSmNkzLOjRSPHQhmtrDYUXORT2)
			dPrint("\tBase32\n\n", l, qHYgMhzFrQZdAuWDGCzFtkvGKPqEMoELooTsAvpwypSVTJsijyEBYsiSmNkzLOjRSPHQhmtrDYUXORT2)
			True


greetUser()
questionOne()
questionTwo()
questionThree()
jvfEbhysidqSClKUzmYdWHEmQLRHjkOZNDbLUsvsHfrnfVROLvbHLjPgZrHOMYBsvcePlctrQnKRMym1 = 454
ttt = 389
WljyoWxVNAGjEMYjOHaXJFFFUFOTeUdlcNBYHwfNfOrKNlRkaOFwLAIFVQnCAzWDHsQsDxBvKQaIaum5 = "LmkKlfJdjmcfVpmMcLIOcMBzMgnxGmWSWbxoEaTHqExwqgHqQYLXNavVOVuYodeiZrJuwjfqDJzXqev"
d7 = "iNTiXzpQIXxiTIiSKAAsJZaxROvUzhusFQWQICUtRWpRmVLGYOmoyhzXuiXYAoHkPqGksjZhRqOCNLs"
aaaAAaaAa = "xLcShCvxHLBrSYvHhGqdHhKhBupoTPBuitBrsRTgTTpwryBuQvDXWliTkfOhGoUylCqaocnrWCKuzZU"
y11 = "oFMcSrNYXkXTwOWHkNjVSErDRybMlBwuPugmzgBxmiNTWGwloFNzukWYfLSvOMKjsORzWtHEaZhLMIQ"
O13 = 124
hhhhhhhhhhhhhhh = "xpaLPIXbuOSwXGFWKVOyXziKUDCrXPtzgPPJXmQGbpHSdHoyaEyRirkPeaHLMupaqeOwsOpXUiByQgB"
mmmmmmmmmmmmmmmmm = "KsHBaxTYwTaWPRIpiUHiUrdqqcxArDWpbJwnrwQkstMDDBdCJshiLrwvXCQmaKNSFDuTSXAZnljUNQT"
IIIIIllIllllIlIIlll = "qLdrHZDdnnrRiWzPljIHjcOfffzxuTWQZvCtCvfjvJHXXoKRgyyiTrRsgqUMMFHFXScVqJeISsrXnfx"
ZZZZZZZZZZZZZZZZZZZZZ = "HuJYPmWLEPzCFQBWIUluueCkPodYCjxWHEjGMbqwPPxzaKRyOzlCjPUwWDobeDleAWnpFwJpInJnOOo"
i1618578639229053723 = 317
NNNNNNNNNNNNNNNNNNNNNNNNN = 360
ggggggggggggggggggggggggggg = "wkSnFbWdMbIgEdHmAVALhhpCififXHWIhQYOzETxLAlAYQHBfonhajOnVDKtFlYCKmDgcyAdToGKGWn"
aaaAaAAAAAAAAAaaAAaaaaAaaaAaA = "EiLZeWRqfUQCucJsQHSoCpdgrFBHyTaCyOjzTlukhzyVjqzoOwcvzbwZQgbeMHgxXYjtGQzIzweKiwy"
KFMuvIGDAcVzbkpPXvueFLQUBOuVoIwVxwcKZYCQobDqCGyGPvyGMKmeXuaZUTIAkDaighzdJBmmueD31 = 309
bFdtwisxDwVDZHRKgIYMZONvicJtqnqBuPOVYcrjGVLSsryFaXejhYJbLXnAQaokosPAlQmmdwhgTUE33 = 291
y1618578639229271735 = "YfhekMlWqVfPyqtmXNJDIfSYLcFqAiYZlVcGPPBkAMAzrbCTQadiIolUoffHbLtXbNPwiIbkVHCVLdC"
lllllIlIlIIIllIIIIllIIlllIllIlllllIlI = 255
YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY = 698
M1618578639229359441 = "tKcBYxIffxomAJoqYbPTZkmiuUJvjOMCBQHINaKlfEBMbidMuKNPvFmzWnKxcjTQpeqXJiiOCeJVGPu"
qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq = 224
q161857863922940745 = "FTmacamNZtfAcBpwewfJteKUegPbHWztBhFRlJRlymcJIgWhXAxumTYiZMoocKoPtrWpfuEsAqEayAF"
c1618578639229442647 = "zlxDdtoalwwgxTqesQSJcLdricCUenXCaeOFjrkkixNCoDkwgcfuuMcVsbGOzdeiIMYZwQRZjezaORO"
i49 = "ZmRvnuZKEVkEcrsyldKZTIKasYyPwkuBvBFUptmMLEVkEOyXQpVYuubcpvNvdGbiEZskQSCpuSjpOAT"
aAAaAaAAAaaaAAAAaaaAAAaAAAAaaAAaaAaAAAAaAAaaAAaaaaA = "rwPoykMxInvpJHUZpUjXDTEGpiKtEmWONxTECIgjVowrhwnDoKrHiLYywVfWyeDAtzSSiOowekyIRnk"
OBzileAAfDpQnFSqUtgVRmOYmMIoGwGijYwBmabrcejzcxEcvoddESTetfkedTEcafLknffXDjLQmtS53 = "dbHILRkMetdQdbQzBqEoOfDKkXxmsbOKmIQMwFmjkHSqFgaWGOGLRUwlyoNYIMSuFSFntwEuparFXUj"
ttttttttttttttttttttttttttttttttttttttttttttttttttttttt = "FroZYTZSltXsgtsYmnXxDqxgxaDcobcOYQQeInywwkuGeRpThhcJRbaIFTxflFQVniifABrtrtxxnKQ"
AaAaaaAaaaAAAAAAAAaaAAAAaaAaaaAaAaAaAAAAaaAAAAaAaAAAaAaAa = 672
IIllIIIIllllIIIIlllllIIIllIlIllIIIllllllllIllIllIlllIlIlIlI = "rNhjXPZEMEDlcDjmuONDrxOMVpiDwBTGphwoAFmpxKswwgvUupSlcFLsSrxpyTzasrLAIPmfEGrnpFy"
oGpKTbMYAOaemHGxgbnyTQIjkLjeYPdsruYapSMYAArrxDWVVFMxuKnykqjeligyETaQkLxhZnFIgvR61 = 588
r1618578639229855563 = "jXbjTicoDcnddtoFJoGGKhSdRDVxooFBHjjFtopSSRrtwGTXXumCkZlzTNdgfyxxiHdusiHTDUcHHNL"
EpPHmicfjSUFpgCxLdZDNSNIudGcKURQyqWJJfGRJCUsoVDbMBrgTQPsKOmZeQISjkuJkqjunkxqMwx65 = "GPDnFNjoYBSrRengaPUUgNevDaJMQPIvgKLQDiATlwsknSeXGwWtQLBBaFsLjediCCGtwCNnRnHVwaU"
qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq = "ozoiDLxXpusEwUsvmKUZLOWlmNVORNGseUQMhjPlYVgCqnViFBCqTCPTRCFiUtSZJydVoSYqbgQNmAb"
aAaaaaAaaaAAAAaaaaAaAAaaaAaaAaaAaAAaAaAaAaaAaaaAaAAAAaAAAaaAaAAAaAAaA = "FIUgICJwKrxDkjYFwlppzpkypzEFZratSJvnpOIqZpPMxOTrFdEiqvCNWwpDxVSCDkCzYWitijJXyUq"
V71 = "zSqgRPFNCjhOHKuqbFRaspsBIISrrRJqYZmSIXkTENmUDFtyouVHJzLloazVYLWGAvJPYvMiEVxUijZ"
lIIlllllIlIlIIIlllIIlIIIIlllIIIIlllllIlIllIllIIIIIlIllIIlllllIIlllIIIllIl = 306
R75 = 737
V77 = 142
jvREZxcwdYlBcYlQyVrDJcLliTdLvdlmcsUyayOkZOCEDeajrnZgUnkErxUyUzZGOZSDgPzCIAAFwhr79 = 489
Y81 = "LHiDFnINKtodbgkFWOULwEDGbACEvtfCwBDKWFdgdUheuFkfFZvcZLPFWTCPPYySgWmyKlWeXowwTVP"
NZGKPrNlJOCQzALmygreZAuHCJlEPEkcmgxIGYXwSoJhBcckTneJgKwcHMwRNWSaLEPxHJbXDDOpVQR83 = 187
h161857863923039385 = "SRhWdsZhnPUwoZFDplVgmqRwhOYuicKDxRAvEKCJBZufyLiKKazwjGoihgNLjpwuZqsbepZaYWqsWTM"
k87 = "cqtAJdEZVYnAPVwXgGoucrMUcidfbUfhdlISTkNpJizviJWtnBugkeNDNYjLcgktwfPpWwiXipwpKhv"
llllllIIIIlIllllIIIIIllllIllIIIlIIllIIIIlIIlllIllllIIllIlIllIllllIlllllllIIIIlIllllIIIllI = "UiQiaFIthyWCeTwpZvnFSTHNKIxAxuFtmmnzeOMECSZldpQZtkngDdBgzlIVqnJTAykSUERSUSpINct"
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM = "AghTyZximAhlomtHXAlcRkpzAvbqYRdgVzlqAmmNInLXcVvVbiMSChuXmkjqFduqOqDbzldBCYdKzLx"
aaAaaAAAAAAaAaaAAAaaaaAAAaAAaAAaAAaAaAaAAaAAAAaAAaAAaaAAAaaaAAaaaAAAAaAaaAaaaaaaAaaaAaAAAAaaa = 424
j95 = "wEjzrgtYqMNoLzMJxPiMhHTEjFspDQlwNRLGNXaSNrvYsqcVspZQklxdedEyJtnqyvjHanJKLnYIDOQ"
AaaAaAaaAAAaaaAaaaaAaaAaAAAaaAaaAaAAaAaAaAAAaAAAAAaaAaAaaaaaAAAAaAAaAaaaAAaaAaaAAAaaaAAaAAAaaaaAA = 186
T99 = 747
aAAaAAAAaaAaAaaaaaaAaAAAAAAAAAAAAAAaaAAAAAaAAAaAaAaAAaAAaAaAaaAaAAaAaAaAaAAAaAAAAAaaaaaAAaaaAAaAAaaaa = "ZkpHLKWJImvmKbzuOQfZbMJgHoOVpLZPMYVCBjgOnOsTLWIigDKdGxodQCnWWRNIUIYfzDKwfgOcJWf"
lllIllIlIlIIlIIIIlllIllIlIIllIIIIllIlIIIIIIlIlIlIIIlIlIlIlIllIIIlIlllIlllllIlIIlIIllllIllllIlIlIIlIIlIl = "RvrKqiNTAWlXzebcahMeICkWtCphciWCiKHcAjowDsKzlPraqTblzAdDPXtZvWyiJhHyvQhwtCzAkQN"
aaAaaAaAaaAaAAaAAAaAaAAAAAaaAaAAaAaaaAAAAAAaAAAAaaAaAAaaAaaAaaAAAaAAAaAAAaAaaaaAAAaaaaaaAaAaaAaAaAaAaaaAA = 579
aaaAaAaaAaAaAAAaaAAAaaaAAaaAAaAAaAAaaaAAaAAAaaAAAaAaaaAAaaAAaAAAAaAaaaaAaaAAaAaaAAAAaaaaAaAAaaaAaaaAAAAAaAA = 206
AAaAaaAaaAAaaaAaaaaAaaAAaAaaAAaaAAaAaaaAaaAaAaaaAAAaAAAAaaAaAAAAaAAaaaAAaAaAaaaAAaaaAAaaAAaAAAaAAaAaAaAaAAAaA = "SogvHuFdyUCcSyruxUYMXpLSRkGFXrecxmLToFGMYHgYTcmEpfmdnzwhkDcHnXyFiJLmoFCMwmpSJqa"
PvSnqPgxhaBBwbovRIeWFOLuoPKZsrpnMrqvMyugKfHWtTsfrBADAtSQPMXEjsUTBAclWdHrnmmAiwZ111 = 293
AAaAaAAAAaAaAAAaaaAAaAAaaAaaAaaAaAAaAAaaAaaAaAaaaaAAaaAAAaAaaAaAAAAAAAaaaaAAAaaAAaAAaAAaAAaAAaaaaaAaAAAAaaaAAAaaA = 423
IIlIllIlllIIlIlIlllIIIIlllIIIIlIlllllIllIIlllIIlIIlIIllIlIIIlllllIllIllIIllIIIllIIIIIIllllIIlIllIIlllIlIlIIlIIIlIlI = "uFYsXgJhhwCmbUjqKYUgTVoYaxdjDphoEjskhdUQXTefghfZhDxjOMtNYyHUSXhQnDKeOJfovhMzstt"
IlIlIlIlIlIlIlIIlIIlIIIIIIIlllIIlIIlllIIIlIlIIlIlllIllIIIlllIllIllllIlIIIllllIIlIIIIlllllIIlllIllIIIlIlIIIllllIlllIll = "YLtnvdyKfBILOdYfBsjrPNVmJllbvsLFQIUjcSJSfwNsSzuBrIUAaTVRrSEUBHslflOpbtsmSzwLXMd"
b119 = 318
w121 = "CqIyXWoxZepRmBuSzcTEhYFxpimLLDRQIhcgtiJJfNaFlQmYuFoKwfKyIhXzgGlhTavorvSGcrYafNP"
LzloUfJKYPdJlpdCKzHrEfexbeLnlqNjzHtKIwegeQTQkRamMDSEtHDxfIobACosfjkukntbSyhNVhY123 = 679
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG = 335
lIIIlllllllIIIllIlllIllIllllIlIllIlIIlllIIIIIIllIlIIlIIIIlllIIIllIlIIllIlIIlIIIllIIllllIIlIlIIllIIIIllIIlllIlIllIIlIIlIlIllIIlI = "EysHXNMxKIwwiDFivJLSbvpJCbTSsZNnynKUNbIOrPwtkcuwfPISAtVLwuLXlLVYUzLIuvbyrjmjPOI"
C16185786392314577129 = 542
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG = 486
j133 = 390
w135 = "mnkxwtqslVTlwYKGMxHzeWIrZesmKDVysyZVaDlVMgWAoAbuKQiUbdNYELkMwmWSBjbgXADkDPeNkGw"
r137 = 776
tEXcrGeNHWVUcTpangqlxNAwiOuXDKiaYxVNvROdtecyRXGUWTgwZRwVebWpmabwVdQXMkewKibyvHl139 = 315
izFPHZszLPKhsCwYNNJJwTzZUXloKGoWoHlNRVaXlPXQssVQXXsCQvpTnqfaOGwLrSCNtpTeOveWKID141 = "beQQdmIsgcIEvaPPXXHjUJcdujmMTaOzGMlBFNqrAMwZHDDonLkKeYLaTCBGwjILBMuCXkNOvVqvEHp"
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF = 540
K145 = 617
aaAAAaAAAAaaaAAaAaaAaaAAaAaaAaaaAaaaAaAAaAaaAaAaaaaaaAAAaaAAaAaaAAaAaAaaAAAAAaaAAaaaaAaAaAAaaaAaaAaAAAAaaAaaAaaAAaaAaaAaAaAaAaAAAAAaAaAaAaAaaaaaaAa = 222
aAAaaaaAAAAAaAAaaAAAAaaAaaaAaAaaaAAaaAaAAAaaaAaAAaaAaAAAaAAaAAaaaaAAAaaAAaAaAAaAaAaaaAaaaaAaAaAAAAaAAaAAaaAaaAAAAaAaAAaAaaaAaaaAaaAAAaaaAaAaAAAAaaaaA = "ObthxEpnEDixfEEeShdDUfbUNxRfdDzxmBWGyZcWoCUeYCamrnMpwtzCOzhGvnVHLHomWZEoMcxZkbf"
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss = 758
uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu = 585
N155 = 370